### ISSUE TITLE
Any chance for a minor release soon?

### ISSUE THREAD

**Issue by trichu1988** [pmaupin/pdfrw#102]
I see the fix for the issue #72 have been merged for months now. So I wonder if any chance a minor release with that is going to come up soon?

**Comment by pmaupin** [comment]
Probably within two weeks.

**Comment by liZe** [comment]
Is there anything we can do to help?

**Comment by pmaupin** [comment]
Hi, liZe, possibly.  Please contact me directly. username at gmail

Thanks,
Pat

**Comment by pmaupin** [comment]
Everything is in the release that I want.  Will try to get it to PyPI this week.

**Comment by liZe** [comment]
[0.4 has been released](https://pypi.python.org/pypi/pdfrw/0.4) :tada:
