### ISSUE TITLE
Extracttext from pdfreader

### ISSUE THREAD

**Issue by praveen049** [pmaupin/pdfrw#103]
Hi
  Are there any examples for extracting text from the pdfreader ?

With 
    `page = doc.getPage(page_nr)`

i get 
    `<class 'pdfrw.objects.pdfdict.PdfDict'>`

but extractText returns NoneType.

Cheers

**Comment by pmaupin** [comment]
pdfrw wasn't designed to extract text, although there is an example in the examples/rl2 subdirectory that can do this in some cases.  You should look at pdfminer.

There is no `extractText` method; the page object has no `extractText` member, and (per Adobe's PDF definition, and unlike standard Python dicts) it is not an error to reference a non-existent member; it is merely the same as referencing a null PDF member.
