### ISSUE TITLE
Remove parts of an pdf

### ISSUE THREAD

**Issue by mumbala** [pmaupin/pdfrw#105]
Hi, i try to remove unwanted parts of an pdf. 

So far i got:

        def remove_images(_inpath, _out_path, *, charset='Latin-1', only_images=True):
            """
            Removes Images from a PDF and saves it as a new PDF
            :param _inpath: path to PDF with images
            :param _out_path: path to PDF without IMAGES
            :param charset: Charset that the PDF is written in
            :return: None
            """
            with open(_inpath, 'rb') as pdf_file:
                pdf_bytes = pdf_file.read()
                pdfreader = PdfReader(fdata=pdf_bytes.decode(charset))

                for page in pdfreader.pages:
                    for xobj in page.Resources.XObject:
                        if only_images and  '/Im' not in xobj: continue
                        try:
                            page['/Resources']['/XObject'].pop(xobj)
                        except: pass

                writer = PdfWriter()
                for page in pdfreader.pages:
                    writer.addpage(page)
                writer.write(_out_path)

if i want to remove all text i can simply do:

        del page['/Resources']['/Font']

if i want to remove all images and other graphical (shadows etc.) content except for background content:
       
        del page['/Resources']['/XObjects']

All those methods leave references inside the pdf, these references can produce errors or warings (like in PDFMiner). What is the proper way of removing stuff from a pdf ? I tried to look up the references e.g. in `page['/Contents']` but the content of this array makes no sense to me. Anyway if i delete `page['/Contents']` every page is blank.

**Comment by pmaupin** [comment]
For one thing, that is canonical pyPDF code.  It is not canonical pdfrw code; you would use, for example, `page.Resources.XObjects = None` in pdfrw, and you would not necessarily open files and convert them to bytes before passing them to pdfrw (you can simply provide the filename).

But yes, removing in a naive fashion will leave dangling references inside the content stream.  pdfrw can parse into most content streams (it would need helpers for embedded images), but it is up to client code to ask it to parse into a content stream, and then to recognize and intelligently remove those references.

You might look at pdfminer; it understands PDF content more deeply.
