### ISSUE TITLE
Flattening PDF File?

### ISSUE THREAD

**Issue by chrisvo** [pmaupin/pdfrw#138]
How do I flatten a filled out PDF file? Is this possible?

Thanks!

**Comment by dougmorin** [comment]
+1 I came here to ask the same thing.

**Comment by gerardojaras** [comment]
me too!

**Comment by powzer** [comment]
I'm trying to do this too.  The only method I've found so far uses pdftk which is not an option for me.

**Comment by MandyMeindersma** [comment]
I mean not using pdfrw but it works :P

`brew install imagemagick@6`
`brew install ghostscript`
`convert {old,new}.pdf` or `convert old.pdf new.pdf`

**Comment by anarchist912** [comment]
I had to solve the flattening after processing PDFs with `pdfrw` and also `fitz`, and i did so by piping it through `ghostscript`.

This would be from the shell:
```bash
gs -dSAFER -dBATCH -dNOPAUSE -dNOCACHE -sDEVICE=pdfwrite -dPreserveAnnots=false -sOutputFile=output.pdf input.pdf
```
Piping it through from a python script could be done this way:
```python
import subprocess
gs_proc = subprocess.Popen("gs -dSAFER -dBATCH -dNOPAUSE -dNOCACHE -sDEVICE=pdfwrite -dPreserveAnnots=false -sOutputFile=%stdout -q -", shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
gs_proc.stdin.write(filled_pdf.read())
gs_proc.stdin.close()
result = gs_proc.stdout.read()
```

**Comment by AlisterH** [comment]
Another option is `qpdf --flatten-annotations=all`
