### ISSUE TITLE
Only works on the first page. 

### ISSUE THREAD

**Issue by sammaroney** [pmaupin/pdfrw#189]
Trying to open a pdf, fill it and save it. But, though my keys are correct, I can only update values on the first page of my pdf, I believe it's because of the "0" in the line "annotations = template_pdf.pages[0][ANNOT_KEY]", but I can't figure out how to fix it. Any pointers greatly appreciated.

My code is:

#! /usr/bin/python

import os
import pdfrw

INVOICE_TEMPLATE_PATH = '/Users/sammaroney/CommonLawFirm/FirmFiles/Lawyer/Templates/ProvincialCourtFamilyForms/F1ApplicationtoObtainanOrder.pdf'
INVOICE_OUTPUT_PATH = '/Users/sammaroney/CommonLawFirm/FirmFiles/Lawyer/Templates/ProvincialCourtFamilyForms/DRAFTEDF1ApplicationtoObtainanOrder.pdf'

ANNOT_KEY = '/Annots'
ANNOT_FIELD_KEY = '/T'
ANNOT_VAL_KEY = '/V'
ANNOT_RECT_KEY = '/Rect'
SUBTYPE_KEY = '/Subtype'
WIDGET_SUBTYPE_KEY = '/Widget'

data_dict = {'CourtFileNum' : 'x',
'CourtLocation' : 'x',
'FMEPNo' : 'x',
'ACauseName' : 'x',
'RCauseName' : 'x',
'AName' : 'x',
'DOB' : 'x',
'Astreet' : 'x',
'Acity' : 'x',
'Aprovince' : 'x',
'Apostal' : 'x',
'Aphone' : 'x',
'Aemail' : 'x',
'Afax' : 'x',
'RName' : 'x',
'Rdob' : 'x',
'Rstreet' : 'x',
'Rcity' : 'x',
'Rprovince' : 'x',
'Rpostal' : 'x',
'Rphone' : 'x',
'Remail' : 'x',
'Rfax' : 'x',
'NoticeOtherPerson1' : 'x',
'NoticeOtherPerson2' : 'x',
'AwantsGuardianship' : 'x',
'AwantsSpousal' : 'x',
'AwantsContact' : 'x',
'AwantsChildSupport' : 'x',
'AwantsPrentTime' : 'x',
'AwantsPO' : 'x',
'AwantsPrentResp' : 'x',
'AwantsOrderOther' : 'x',
'OrderOtherDetails' : 'x',
'NoPastOrders' : 'x',
'OrdersAttached' : 'x',
'NoPastAgreements' : 'x',
'Text1' : 'x',
'Kid1name' : 'x',
'Kid1dob' : 'x',
'Kid2name' : 'x',
'Kid2dob' : 'x',
'Kid3name' : 'x',
'Kid3dob' : 'x',
'Kid4name' : 'x',
'Kid4dob' : 'x',
'Arship2Kids' : 'x',
'Rrship2Kids' : 'x',
'ArrangeKidsCurrent' : 'x',
'AwantsKidsDetails' : 'x',
'CaseName' : 'x',
'CourtFileNum2' : 'x',
'CurrentSupportArrange' : 'x',
'AestimateRincome' : 'x',
'AestimateRincomeReasons' : 'x',
'AwantsChildSuppGuidelineAmount' : 'x',
'NumKids' : 'x',
'AwantsS7' : 'x',
'AwantsS7Details' : 'x',
'AwantsCSuppRetro' : 'x',
'CSuppRetroDate' : 'x',
'CSuppRetroReason' : 'x',
'AwantsSSuppRetro' : 'x',
'SSuppRetroDate' : 'x',
'SSuppRetroReason' : 'x',
'AwantsPOterms' : 'x',
'ALawyerName' : 'x',
'ALawyerName2' : 'x',
'AName2' : 'x',
'ALawyerName3' : 'x',
'ServerName' : 'x',
'ServerOccupation' : 'x',
'ServerAddress' : 'x',
'ServedName' : 'x',
'ServiceDate' : 'x',
'ServiceAddress' : 'x',
'ServedATOO' : 'x',
'ServedExhibitA' : 'x',
'ServedExhibitALetter' : 'x',
'ServedExhibitAName' : 'x',
'ServedExhibitB' : 'x',
'ServedExhibitBLetter' : 'x',
'ServedExhibitBName' : 'x',
'ServedExhibitC' : 'x',
'ServedExhibitCLetter' : 'x',
'ServedExhibitCName' : 'x',
'ServedExhibitD' : 'x',
'ServedExhibitDLetter' : 'x',
'ServedExhibitDName' : 'x',
'ServedBlankReply' : 'x',
'ServedBlankF4' : 'x'
}

def write_fillable_pdf(input_pdf_path, output_pdf_path, data_dict):
    template_pdf = pdfrw.PdfReader(input_pdf_path)
    annotations = template_pdf.pages[0][ANNOT_KEY]
    for annotation in annotations:
        annotation.update(pdfrw.PdfDict(AP=''))
        if annotation[SUBTYPE_KEY] == WIDGET_SUBTYPE_KEY:
            if annotation[ANNOT_FIELD_KEY]:
                key = annotation[ANNOT_FIELD_KEY][1:-1]
                if key in data_dict.keys():
                    annotation.update(
                        pdfrw.PdfDict(V='{}'.format(data_dict[key]))
                    )
    pdfrw.PdfWriter().write(output_pdf_path, template_pdf)

if __name__ == '__main__':
    write_fillable_pdf(INVOICE_TEMPLATE_PATH, INVOICE_OUTPUT_PATH, data_dict)

**Comment by sammaroney** [comment]
`# from mailmerge import MailMerge
# import os
# # template = '/Users/sammaroney/CommonLawFirm/FirmFiles/Lawyer/Templates/ProvincialCourtFamilyForms/' + str(FormChoice) + str(BCPCForms[FormChoice])+".docx"
# template = "/Users/sammaroney/CommonLawFirm/FirmFiles/Lawyer/Templates/ProvincialCourtFamilyForms/F4FinancialStatement.docx"
# document = MailMerge(template)
# foobar = ""
# merge_fields = document.get_merge_fields()
# for field in merge_fields:
#     foobar += ("%s = \"%s\"," % (field,raw_input("%s:"%field)))
# print foobar
# print "Copy this ^ line and paste it in the PASTEHERE spot in the code, then come back and hit enter"
# raw_input("")
# document.merge(
# TestField = "Test",
# CourtFileNumber = "One!")
# document.write("/Users/sammaroney/CommonLawFirm/Clients/DraftedForms/DRAFTED.docx")
# print "Success!"
#! /usr/bin/python

import os
import pdfrw


INVOICE_TEMPLATE_PATH = '/Users/sammaroney/CommonLawFirm/FirmFiles/Lawyer/Templates/ProvincialCourtFamilyForms/F1ApplicationtoObtainanOrder.pdf'
INVOICE_OUTPUT_PATH = '/Users/sammaroney/CommonLawFirm/FirmFiles/Lawyer/Templates/ProvincialCourtFamilyForms/DRAFTEDF1ApplicationtoObtainanOrder.pdf'


ANNOT_KEY = '/Annots'
ANNOT_FIELD_KEY = '/T'
ANNOT_VAL_KEY = '/V'
ANNOT_RECT_KEY = '/Rect'
SUBTYPE_KEY = '/Subtype'
WIDGET_SUBTYPE_KEY = '/Widget'

data_dict = {'CourtFileNum' : 'x',
'CourtLocation' : 'x',
'FMEPNo' : 'x',
'ACauseName' : 'x',
'RCauseName' : 'x',
'AName' : 'x',
'DOB' : 'x',
'Astreet' : 'x',
'Acity' : 'x',
'Aprovince' : 'x',
'Apostal' : 'x',
'Aphone' : 'x',
'Aemail' : 'x',
'Afax' : 'x',
'RName' : 'x',
'Rdob' : 'x',
'Rstreet' : 'x',
'Rcity' : 'x',
'Rprovince' : 'x',
'Rpostal' : 'x',
'Rphone' : 'x',
'Remail' : 'x',
'Rfax' : 'x',
'NoticeOtherPerson1' : 'x',
'NoticeOtherPerson2' : 'x',
'AwantsGuardianship' : 'x',
'AwantsSpousal' : 'x',
'AwantsContact' : 'x',
'AwantsChildSupport' : 'x',
'AwantsPrentTime' : 'x',
'AwantsPO' : 'x',
'AwantsPrentResp' : 'x',
'AwantsOrderOther' : 'x',
'OrderOtherDetails' : 'x',
'NoPastOrders' : 'x',
'OrdersAttached' : 'x',
'NoPastAgreements' : 'x',
'Text1' : 'x',
'Kid1name' : 'x',
'Kid1dob' : 'x',
'Kid2name' : 'x',
'Kid2dob' : 'x',
'Kid3name' : 'x',
'Kid3dob' : 'x',
'Kid4name' : 'x',
'Kid4dob' : 'x',
'Arship2Kids' : 'x',
'Rrship2Kids' : 'x',
'ArrangeKidsCurrent' : 'x',
'AwantsKidsDetails' : 'x',
'CaseName' : 'x',
'CourtFileNum2' : 'x',
'CurrentSupportArrange' : 'x',
'AestimateRincome' : 'x',
'AestimateRincomeReasons' : 'x',
'AwantsChildSuppGuidelineAmount' : 'x',
'NumKids' : 'x',
'AwantsS7' : 'x',
'AwantsS7Details' : 'x',
'AwantsCSuppRetro' : 'x',
'CSuppRetroDate' : 'x',
'CSuppRetroReason' : 'x',
'AwantsSSuppRetro' : 'x',
'SSuppRetroDate' : 'x',
'SSuppRetroReason' : 'x',
'AwantsPOterms' : 'x',
'ALawyerName' : 'x',
'ALawyerName2' : 'x',
'AName2' : 'x',
'ALawyerName3' : 'x',
'ServerName' : 'x',
'ServerOccupation' : 'x',
'ServerAddress' : 'x',
'ServedName' : 'x',
'ServiceDate' : 'x',
'ServiceAddress' : 'x',
'ServedATOO' : 'x',
'ServedExhibitA' : 'x',
'ServedExhibitALetter' : 'x',
'ServedExhibitAName' : 'x',
'ServedExhibitB' : 'x',
'ServedExhibitBLetter' : 'x',
'ServedExhibitBName' : 'x',
'ServedExhibitC' : 'x',
'ServedExhibitCLetter' : 'x',
'ServedExhibitCName' : 'x',
'ServedExhibitD' : 'x',
'ServedExhibitDLetter' : 'x',
'ServedExhibitDName' : 'x',
'ServedBlankReply' : 'x',
'ServedBlankF4' : 'x'
}

def write_fillable_pdf(input_pdf_path, output_pdf_path, data_dict):
    template_pdf = pdfrw.PdfReader(input_pdf_path)
    annotations = template_pdf.pages[0][ANNOT_KEY]
    for annotation in annotations:
        annotation.update(pdfrw.PdfDict(AP=''))
        if annotation[SUBTYPE_KEY] == WIDGET_SUBTYPE_KEY:
            if annotation[ANNOT_FIELD_KEY]:
                key = annotation[ANNOT_FIELD_KEY][1:-1]
                if key in data_dict.keys():
                    annotation.update(
                        pdfrw.PdfDict(V='{}'.format(data_dict[key]))
                    )
    pdfrw.PdfWriter().write(output_pdf_path, template_pdf)



if __name__ == '__main__':
    write_fillable_pdf(INVOICE_TEMPLATE_PATH, INVOICE_OUTPUT_PATH, data_dict)
`

**Comment by oahdoot** [comment]
You can loop through all the pages and annotations:

```
    pages = template_pdf.pages
    for page in pages:
        annotations = page[ANNOT_KEY]
        if annotations:  # Edited to add this in
```

**Comment by sammaroney** [comment]
Thank you for your help! That worked well.

**Comment by oahdoot** [comment]
@sammaroney One addendum - make sure you add the following code to make sure your pdfrw doesnt break if one of the pages doesn't have any fillable fields on it:

`if annotations:`

So the full code would be:

```
    pages = template_pdf.pages
    for page in pages:
        annotations = page[ANNOT_KEY]
        if annotations:

```
