### ISSUE TITLE
Setting a checkbox annotation to preferred state .

### ISSUE THREAD

**Issue by AnderssonDavid** [pmaupin/pdfrw#196]
When I set a checkbox to checked/unchecked (Yes/Off), the change is only visible by using Google Chrome. Adobe Acrobat, PDFxChange, Edge and internet explorer does not see if I have the checkbox checked.

The Python code:

```python
import os
import pdfrw

INVOICE_TEMPLATE_PATH = 'invoice_template.pdf'
INVOICE_OUTPUT_PATH   = 'invoice_output.pdf'

ANNOT_KEY = '/Annots'
ANNOT_FIELD_KEY = '/T'
SUBTYPE_KEY = '/Subtype'
WIDGET_SUBTYPE_KEY = '/Widget'

def write_fillable_pdf(input_pdf_path, output_pdf_path, data_dict):
    template_pdf = pdfrw.PdfReader(input_pdf_path)
    annotations = template_pdf.pages[0][ANNOT_KEY]
    for annotation in annotations:
        if annotation[SUBTYPE_KEY] == WIDGET_SUBTYPE_KEY:
            if annotation[ANNOT_FIELD_KEY]: 
                key = annotation[ANNOT_FIELD_KEY][1:-1]
                if key in data_dict.keys():
                    if (key[0:8] == 'CheckBox') and  (data_dict[key] == 'Yes') :
                        annotation.update( pdfrw.PdfDict(  AS='Yes'  ) )
    
    template_pdf.Root.AcroForm.update(pdfrw.PdfDict(NeedAppearances=pdfrw.PdfObject('true')))
    pdfrw.PdfWriter().write(output_pdf_path, template_pdf)


data_dict = {
    'item_1_amount': '123',
    'CheckBox1': 'Yes'  }

if __name__ == '__main__':
    write_fillable_pdf(INVOICE_TEMPLATE_PATH, INVOICE_OUTPUT_PATH, data_dict)
```

When comparing the pdf before and after pdfrw has writen annot value, pdfrw puts the value within parenthesis, compared to if checked by e PDF reader. 

The output when the checkbox is check by a pdf reader program: `'/V': '/Yes'` 
The output when the checkbox is check by pdfrw:                          `'/V': '(Yes)'` 

Is this why the checked boxes can't be seen in other pdf readers?  How do I set the value without parenthesis?

[Here is a picture where I have compiled the parameters before and after](https://i.imgur.com/zFIxwNv.png)

**Comment by AnderssonDavid** [comment]
Oh I found the problem myself. I needed to use `pdfrw.PdfName`. 

```python
import os
import pdfrw

INVOICE_TEMPLATE_PATH = 'invoice_template.pdf'
INVOICE_OUTPUT_PATH   = 'invoice_output.pdf'

ANNOT_KEY = '/Annots'
ANNOT_FIELD_KEY = '/T'
ANNOT_FORM_type = '/FT'         # Form type (e.g. text/button)
ANNOT_FORM_button = '/Btn'      # ID for buttons, i.e. a checkbox
ANNOT_FORM_text = '/Tx'         # ID for textbox
SUBTYPE_KEY = '/Subtype'
WIDGET_SUBTYPE_KEY = '/Widget'

def write_fillable_pdf(input_pdf_path, output_pdf_path, data_dict):
    template_pdf = pdfrw.PdfReader(input_pdf_path)
    for Page in template_pdf.pages:
        if Page[ANNOT_KEY]:
            for annotation in Page[ANNOT_KEY]:
                if annotation[ANNOT_FIELD_KEY] and annotation[SUBTYPE_KEY] == WIDGET_SUBTYPE_KEY :
                    key = annotation[ANNOT_FIELD_KEY][1:-1] # Remove parentheses
                    if key in data_dict.keys():
                        if annotation[ANNOT_FORM_type] == ANNOT_FORM_button:
                            # button field i.e. a checkbox
                            annotation.update( pdfrw.PdfDict( V=pdfrw.PdfName(data_dict[key]) , AS=pdfrw.PdfName(data_dict[key]) ))
                        elif annotation[ANNOT_FORM_type] == ANNOT_FORM_text:
                            # regular text field
                            annotation.update( pdfrw.PdfDict( V=data_dict[key], AP=data_dict[key]) )
    template_pdf.Root.AcroForm.update(pdfrw.PdfDict(NeedAppearances=pdfrw.PdfObject('true')))
    pdfrw.PdfWriter().write(output_pdf_path, template_pdf)

data_dict = {
    'item_1_amount': '123',
    'CheckBox1': 'Yes'  }

if __name__ == '__main__':
    write_fillable_pdf(INVOICE_TEMPLATE_PATH, INVOICE_OUTPUT_PATH, data_dict)
```

**Comment by rainer85ah** [comment]
@AnderssonDavid How would you load a png image into an image annotation field?
Which arguments would you use here? I'm looking for the equivalent for an image instead of a text field.
annotation.update(pdfrw.PdfDict(AP=data_dict[key], V='{}'.format(data_dict[key])))

{'/A': {'/JS': '(event.target.buttonImportIcon\\(\\);)', '/S': '/JavaScript'}, '/AP': {'/N': (94, 0)}, '/DA': '(/HeBo 12 Tf 0 g)', '/F': '4', '/FT': '/Btn', '/Ff': '65536', '/MK': {'/BC': ['0.75293'], '/BG': ['1.0', '1.0', '1.0'], '/TP': '1'}, '/P': (7, 0), '/Rect': ['114.995', '53.7945', '242.349', '84.288'], '/Subtype': '/Widget', '/T': '(user_signature_af_image)', '/Type': '/Annot', '/AS': '/Image', '/V': }

**Comment by AnderssonDavid** [comment]
@rainer85ah I'm not sure. I have not needed to work with images.  [Here is a reference manual for PDF's](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf)
