### ISSUE TITLE
New releases on Github

### ISSUE THREAD

**Issue by edumco** [pmaupin/pdfrw#206]
## Will you release a new version on Github / PyPI ?

Since the 0.4 release there are severel commits on master branch.

Would be nice to have a 0.5 version. What do you think?

**Comment by fdemmer** [comment]
duplicate of #195, please check existing issues before adding to the noise.

**Comment by t-houssian** [comment]
I released a updated fork that helped me a lot on pypi. https://pypi.org/project/pdfrw2/
Also have been working on a building onto and adding to the project at https://github.com/t-houssian/fillpdf

**Comment by edumco** [comment]
Thanks, @t-houssian. I'm closing the issue here and move the efforts to this new repo.
