### ISSUE TITLE
Importing * from pdfrw and pdfrw.objects doesn't work

### ISSUE THREAD

**Issue by Unrud** [pmaupin/pdfrw#35]
The `__all__` list in `__init__.py` must contain strings with the names of modules not the modules itself.

https://docs.python.org/2/tutorial/modules.html#importing-from-a-package

**Comment by pmaupin** [comment]
I think you mean names of functions, but yeah...

**Comment by pmaupin** [comment]
Fix checked in.  It's interesting that nobody noticed that brain-fart before -- maybe most people start with one of the examples.
