### ISSUE TITLE
How to remove object from pdf

### ISSUE THREAD

**Issue by b4stien** [pmaupin/pdfrw#42]
I'm sorry for posting something which is not directly an issue (and I'll be glad to push a PR for the docs with the answer !).

I try to remove some objects (mostly images) from an existing pdf, i can find them with `pdfrw. findobjs.find_objects()`, but I have no clue how to remove them from "the tree"... Can you provide any kind of guidance (or place to look for more resources?).

Many thanks,

**Comment by pmaupin** [comment]
The first level of removal would be to simply replace the object in the tree with, e.g. a small blank image.  If that is good enough, once you know the object you care about, you can re-traverse the tree and remove it from the dictionary it is in (or remember enough about the tree during the traversal to remove it).

The next level of removal would be to remove the reference to the image.  That requires decompressing (if it is compressed) the graphic stream (which pdfrw sometimes can do, but doesn't support all compressions) and then parsing it for a reference to the image.  That's a bit trickier.  The code in the examples/rl2 directory can do some of this parsing, but chokes on some fonts.

**Comment by pmaupin** [comment]
Let me know if this is clear as mud, or if you have any further questions or information about your requirements.

Thanks,
Pat

**Comment by b4stien** [comment]
It's super clear, I ended up doing something like:

    with open('test.pdf', 'rb') as pdf_file:
        pdf_bytes = pdf_file.read()
        dict_pages = PdfReader(fdata=pdf_bytes.decode('Latin-1')).pages
        dict_pages[0].pop('/SomeKey')

        writer = PdfWriter()
        for page in dict_pages:
            writer.addpage(page)
        writer.write('test_output.pdf')

Thanks a lot for your time, great project!

**Comment by ao2** [comment]
Hi, I just wanted to expand on @b4stien answer, I wrote a simple program to remove objects from a pdf files by specifying the objects IDs.

Check it out:
https://git.ao2.it/pdfstrip.git/

And some back-story:
https://ao2.it/121
https://twitter.com/ao2it/status/740633644818169863

Ciao,
   Antonio
