### ISSUE TITLE
Another release?

### ISSUE THREAD

**Issue by Roguelazer** [pmaupin/pdfrw#51]
I would like to use pdfrw for a project, but it involves in-memory PDFs and runs on Python 3.x, so I'm stuck using a git+ssh:// URL to install it, which is somewhat problematic. Any chance of a new release including #43 / 9e4aa55552b2db117ea3479bf43271d554055dbf getting pushed to pypi?

**Comment by oz123** [comment]
Yes, please make a 0.3 release or something. The current release on PyPI is broken

**Comment by takluyver** [comment]
I've also just run into the same issue, and found that installing from Github works.

@pmaupin is there anything particular you're hoping to get done before making another release? Can we do anything to help it move forwards?

**Comment by takluyver** [comment]
I've volunteered to do a bit of maintenance while Patrick is busy with other things. I don't know much about the PDF format, so I'm going to be staying fairly conservative with things like bug fixes. In any case, I have just uploaded a new version to PyPI, so this should should work without needing a development version now.
