### ISSUE TITLE
RE: PdfReader cannot read the io.BytesIO properly in Python 3.5

### ISSUE THREAD

**Issue by LiuGavin** [pmaupin/pdfrw#59]
It seems there is a "tab/space" issue on line 499 in pdfreader.py, where it currently only do the 'convert_load' in case of file, but not from 'in-memory'(such as BytesIO) object. Ideally it should be done in both case, so I believe this is a typo that mis-place the line "fdata=conver_load(fdata)" into the 'file-reading' section only.

After I fix the 'tab' issue above(so that it applies for both case), I can use it for BytesIO object now.

By the way, it seems this bug only occurs in Python 3.5, I don't have any issue with Python 3.4.

**Comment by takluyver** [comment]
This should be fixed in pdfrw 0.3, which was just released.
