### ISSUE TITLE
how to set unicode info?

### ISSUE THREAD

**Issue by retsyo** [pmaupin/pdfrw#64]
I mean use non-english chanracters, for example
writer.trailer.Info = IndirectPdfDict(
    Title=u'unicode string1',
    Author=u'unicode string2',
)

thanks

**Comment by pmaupin** [comment]
Sorry, no good way as of yet.  Need to get one of the PRs for unicode support added.  Hopefully soon.

**Comment by pmaupin** [comment]
Fixed by PR #81.
