### ISSUE TITLE
How to navigate through the tree to see the PDF text content.

### ISSUE THREAD

**Issue by abhinavbom** [pmaupin/pdfrw#66]
I am trying to navigate through the tree created by PdfReader and looking for the var that stores the text of PDF. 

```
>>> x.pages[1].Resources
{'/Font': {'/T1_2': (14, 0), '/T1_3': (16, 0), '/T1_0': (146, 0), '/T1_1': (148, 0)}, '/ProcSet': ['/PDF', '/Text']}
>>> x.pages[1].Resources.ProcSet
['/PDF', '/Text'] 
```

Not sure if this is the correct way of doing it.

**Comment by pmaupin** [comment]
PDFs are very complicated.  But usually the text is in the stream attribute of the Contents dictionary of the page.
