### ISSUE TITLE
Xobjects with compression parameters not supported

### ISSUE THREAD

**Issue by maralad** [pmaupin/pdfrw#72]
Was getting this when trying to merge this pdf:
http://demo.visualid.com/_mediafiles/demo/_tmp/3GoeKXdVeEk7.pdf
Int this pdf:
https://s3-eu-west-1.amazonaws.com/visualid-mediafiles/demo/20170131/AC1E00B70333d13AF9qXE39A3E9A/9sd9DGiaS4X4.pdf

FlateDecode needs to decompress and recompress
Here is thd dict of parameters in the pdf...
[{'/Length': '3134', '/Filter': '/FlateDecode'}, {'/Length':
'3172',
 '/Filter': '/FlateDecode'}, {'/Length': '3597', '/Filter':
'/FlateDecode'},
{'/Length': '3580', '/Filter': '/FlateDecode'}, {'/Length': '3044',
 '/Filter': '/FlateDecode'}, {'/Length': '3393', '/Filter':
'/FlateDecode'},
{'/Length': '3347', '/Filter': '/FlateDecode'}, {'/Length': '3223',
 '/Filter': '/FlateDecode'}]

Code fix by @pmaupin to come

**Comment by pmaupin** [comment]
PR #73 merged
