### ISSUE TITLE
Question : how to remove some elements in a pdf file ?

### ISSUE THREAD

**Issue by setop** [pmaupin/pdfrw#74]
I'm trying to make a script to remove some images from a pdf file based on their dimension.

Iterating over pages,
* if I use `findobjs.find_objects(page, valid_subtypes=(PdfName.Image,))`, it finds Image objects and I can check width and height properties. But then the link with the parent (the page) is lost so I'm not able to remove this element from the page.
* if I use `find_objects` on each content of the page (page.Contents), so I can keep the link with the page, it is not able to find any Image object.

I've tried to understand `find_objects` function to mock the behavior in a custom function. But there is some magic around `obj.iteritems()` that I don't get.

Do you have any idea on how to proceed ?

**Comment by pmaupin** [comment]
Unless it's an inline image (very rare), there will be a reference to the dict key for the image XObject inside the content stream, but the image XObject does not itself reside in `page.Contents`; rather it resides in the `page.Resources.XObject` dictionary.

So, you could search in `page`, or `page.Resources`, or `page.Resources.XObject`, but if you search in `page.Contents`, you are looking in the wrong place.

If by "magic" you mean the nofollow stuff, that's just to keep the `obj.iteritems` from being stuck in a loop -- each page object references its parent...

**Comment by setop** [comment]
Hey, thanks you for the hint !
Images are indeed in `page.Resources.XObject`.
There is no magic after all, just knowledge.
Now my script works.
Thanks a lots.
