### ISSUE TITLE
Opening document with PdfReader fails of a flattened PDF document.

### ISSUE THREAD

**Issue by fwdevmobile** [pmaupin/pdfrw#76]
I have a PDF document with an Acroform in it. After filling in values and flattening the document, I tried to open the document again with the PdfReader, but this fails. It gives me the following stacktrace.

Error stacktrace:

```
../../.virtualenvs/pdftools35/lib/python3.5/site-packages/pdfrw/pdfreader.py:546: in __init__
    trailer, is_stream = self.parsexref(source)
../../.virtualenvs/pdftools35/lib/python3.5/site-packages/pdfrw/pdfreader.py:439: in parsexref
    return self.parse_xref_stream(source), True
../../.virtualenvs/pdftools35/lib/python3.5/site-packages/pdfrw/pdfreader.py:372: in parse_xref_stream
    xtype, p1, p2 = islice(get, 3)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s = '\x00\x00\x00\x00ÿÿ\x01\x00\x00\x12\x00\x00\x01\x00\x02\x02\x00\x00\x01\x00\x12[\x00\x00\x01\x00\x13\x94\x00\x00\x01\x...12\x00\x00\x01\x01ãc\x00\x00\x01\x01ãÜ\x00\x00\x01\x01ä-\x00\x00\x01\x01ä¦\x00\x00\x01\x01ä÷\x00\x00\x01\x01åq\x00\x00'
lengths = <itertools.cycle object at 0x120fb4e08>

    def readint(s, lengths):
        lengths = itertools.cycle(lengths)
        offset = 0
        for length in itertools.cycle(lengths):
            next = offset + length
            # if isinstance(s, str):
            #    s = bytes(s, 'latin-1')
    
>           yield int(hexlify(s[offset:next]), 16) if length else None
E           TypeError: a bytes-like object is required, not 'str'

../../.virtualenvs/pdftools35/lib/python3.5/site-packages/pdfrw/pdfreader.py:342: TypeError
```

I am using Python 3.5.1.

My test code:

```python
import pdfrw

with open('document_after_flattening.pdf', 'rb') as f:
    fdata = f.read().decode('latin-1')
    pdfrw.PdfReader(fdata=fdata)

```

I have traced the error back to :

```python
        def readint(s, lengths):
            lengths = itertools.cycle(lengths)
            offset = 0
            for length in itertools.cycle(lengths):
                next = offset + length
                yield int(hexlify(s[offset:next]), 16) if length else None
                offset = next
```

```python
hexlify(s[offset:next])
```

I replaced the code above with:
```python
        def readint(s, lengths):
            lengths = itertools.cycle(lengths)
            offset = 0
            for length in itertools.cycle(lengths):
                next = offset + length


                if isinstance(s, str):
                   s = bytes(s, 'latin-1')


                yield int(hexlify(s[offset:next]), 16) if length else None
                offset = next
```

It appears that the stream is a string and the function didn't expect this and that's the reason why it crashes.

The document
[document_before_flattening.pdf](https://github.com/pmaupin/pdfrw/files/858278/document_before_flattening.pdf)

[document_after_flattening.pdf](https://github.com/pmaupin/pdfrw/files/858277/document_after_flattening.pdf)

**Comment by pmaupin** [comment]
Thank you for analyzing and reporting this!

I guess not that many pdfrw users who aren't on 2.7 encounter cross-reference streams, or this would have been noticed before.  We should add your "after" PDF to the regression suite.

In looking at `readint()` it is apparent that there are redundant calls to `itertools.cycle()` as well.

I don't believe your fix is appropriate for Python 2.7.  I believe the right answer is to make two changes to pdfreader.  First, import convert_store:

```
-from .py23_diffs import convert_load, iteritems
+from .py23_diffs import convert_load, convert_store, iteritems
``` 

and second, use it on the string (and incidentally, remove the redundant call to itertools.cycle())"

```
        def readint(s, lengths):
-            lengths = itertools.cycle(lengths)
+            s = convert_store(s)
            offset = 0
            for length in itertools.cycle(lengths):
                next = offset + length
                yield int(hexlify(s[offset:next]), 16) if length else None
                offset = next
```

Thoughts?

Thanks again,
Pat

**Comment by pmaupin** [comment]
So, it turns out one reason very few people noticed this is that your compressed xref stream isn't actually compressed...  Generic fix coming shortly.

**Comment by fwdevmobile** [comment]
That is great to hear. Thanks. I had the intention to do some research for the cause, but you found it already.  Great job.
