### ISSUE TITLE
Lost links? [rl1/subset.py]

### ISSUE THREAD

**Issue by lzy0699** [pmaupin/pdfrw#89]
I use reportlab to generate a pdf file that contains some linkRects and linkURLs.Then I use  'rl1/subset.py' to creat a copy.The copy lost all links.Why?

**Comment by pmaupin** [comment]
That would be a good thing; it just hasn't happened, although if you look at a few of the other issues, you will see that some users have done (and shared) some link code specific to their own needs.

pdfrw excels in print flows (where it's really fast) and in reusing parts of old PDFs with reportlab (where there's no free competition that I know of; reportlab's pagecatcher is quite expensive, I'm told).  Neither of those use-cases require link preservation, and I think other tools such as pyPdf2 and pdftk support links, so there hasn't really been that much pressure.  

PDFs are overcomplicated and nobody's submitted a PR with code (and tests!) to correctly preserve valid links for pdfrw yet (and toss the invalid ones).  Although many PDF viewers are really good at coping with incorrect PDFs, it is the goal of pdfrw not to produce those.  We also don't want dangling references that cause all the pages you thought you got rid of to wind up in the actual file, even though they're not viewable.

**Comment by lzy0699** [comment]
Thank you for your answer！
