### ISSUE TITLE
[Feature Request]  Extract full pages to image files

### ISSUE THREAD

**Issue by bjubb** [pmaupin/pdfrw#96]
i'm currently using JPedal to convert full pages to images (PNG for example).   Does this library have that capability - or can a PNGWriter instance be used/written to encode one from the PdfReader ?

**Comment by wjehenddher** [comment]
FWIW, we use Wand (imagemagick) to convert a PDF page to PNG (trying to honor page geometry)

**Comment by pmaupin** [comment]
pdfrw does not have a pixel drawing canvas.
