### ISSUE TITLE
Is BleedBox (and other rectangles) available/supported?

### ISSUE THREAD

**Issue by wjehenddher** [pmaupin/pdfrw#97]
http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf
Section 14.11.2 Page Boundaries, 14.11.2.1 General

Just curious although we only use `MediaBox` at the moment

```python
r = pdfrw.PdfReader("...pdf")
r.pages[0].inheriable.MediaBox
r.pages[0].inheriable.CropBox
# Other rectangles ?
```

**Comment by pmaupin** [comment]
You can certainly read and set any of the rectangles on the pages.

But (for example) the bleedbox is not defined to be inheritable by Adobe.

**Comment by wjehenddher** [comment]
Thank you @pmaupin 

I was wondering if they were already accessible somehow. I searched the project for "bleed" and I didn't find it so I asked.

Thanks again!
